AllCops:
  TargetRubyVersion: 2.5

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - "bin/**/*"
    - "Gemfile"
    - "Rakefile"

Style/StringLiterals:
  EnforcedStyle: double_quotes
